- name: This playbook will download application jar file from JFrog Artifactory to your local machine
  hosts: localhost
  tasks:
  - name: Download frontend jar from JFrog Artifactory
    get_url:
      url: "http://localhost:8082/artifactory/tektutor/org/tektutor/fe/1.0.0/fe-1.0.0.jar"
      dest: .
      url_username: "admin"
      url_password: "Admin@123"


